### ISSUE TITLE
Release on hex

### ISSUE THREAD

**Issue by NobbZ** [lizenn/erlang-dbus#10]
release it on hex.pm so we can use it as a dependency easily in `rebar3` or elixir projects

**Comment by jeanparpaillon** [comment]
Fixed in 19d1b196567b612ebb473c558575d00c99d6f633
Neverteless, there is already a dbus application on hex.pm.
@fringel Could you check how to avoid conflict ?

**Comment by ffringel** [comment]
Ok. Checking on that.

**Comment by ffringel** [comment]
Just update the dbus application on Hex.pm

**Comment by jeanparpaillon** [comment]
Hi @ffringel , I am unable to update dbus package on hex.pm
Can you add me as owner of the package ?

Cheers !

**Comment by ffringel** [comment]
OK.

**Comment by jeanparpaillon** [comment]
Package updated on hex.pm:
https://hex.pm/packages/dbus

@ffringel 
Sorry for the delay
