### ISSUE TITLE
Prepare for OTP integration

### ISSUE THREAD

**Issue by saa** [lizenn/erlang-dbus#16]
@jeanparpaillon I have questions. And I want start from this "use OTP-style Makefiles". What do you mean? I look at https://github.com/richcarl/merl/blob/master/Makefile (was include to otp) and need make similar?

**Comment by saa** [comment]
Also, maybe I can start work on it https://github.com/lizenn/erlang-dbus/issues/8 but in separate branch?

**Comment by jeanparpaillon** [comment]
That would be great !
You can work on your own fork, and I will integrate in a separate branch your pull requests.

**Comment by saa** [comment]
Good. You can bit explain about "use OTP-style Makefiles"?

**Comment by jeanparpaillon** [comment]
OTP applications uses some some makefile libraries / variables / etc (see https://github.com/erlang/otp/tree/maint/make) . erlang-dbus uses erlang.mk.

**Comment by saa** [comment]
Ah, got it, I thought maybe other things. So will be work in a separate branch.

**Comment by jeanparpaillon** [comment]
Sure, that kind of feature really deserve a separate branch before merging. Thanks

**Comment by saa** [comment]
Good, about my proposal. I start it on google docs and link you, ok? In IRC private message?

**Comment by jeanparpaillon** [comment]
Ok for google docs

**Comment by saa** [comment]
@jeanparpaillon review please and I need your feedback https://docs.google.com/document/d/1gTjyVzGuUzuDkQ9HF3xM5atPJe-aEE8j02X8lFMcCsk/edit?usp=sharing

**Comment by jeanparpaillon** [comment]
@saa : done, thanks for this sound proposal. Rationale and obectives looks clear. With a risk management plan it should be perfect.

**Comment by saa** [comment]
@jeanparpaillon thanks for review. Right now I doing fixes and ping your again and if all is ok I will upload it to gsoc site.

**Comment by saa** [comment]
@jeanparpaillon updated

**Comment by jeanparpaillon** [comment]
Ok

**Comment by saa** [comment]
@jeanparpaillon fixed. All is ok and I can upload it on GSoC site?

**Comment by jeanparpaillon** [comment]
Go :)

**Comment by saa** [comment]
@jeanparpaillon Thanks for choose. I see a great work.

**Comment by jeanparpaillon** [comment]
Congrats. Glad to work with you !
I'm looking forward for your contribs.

**Comment by jeanparpaillon** [comment]
Let's follow this on https://github.com/lizenn/erlang-dbus/wiki/IntegrationOTP
