### ISSUE TITLE
String size limit ?

### ISSUE THREAD

**Issue by jeanparpaillon** [lizenn/erlang-dbus#18]
This bug looks like string size limit:
https://github.com/erocci/erocci_backend_dbus/issues/10

**Comment by ffringel** [comment]
Hello @jeanparpaillon can you illustrate more about this bug? Would love to take a look at it.

**Comment by jeanparpaillon** [comment]
@ffringel  : the bug appears when erlang code calls a function returning a string > 16 kB.
I think the first thing would be to reproduce it in a smaller test case, before trying to fix it

**Comment by ffringel** [comment]
OK. Could you provide a test case which causes the bug?

**Comment by jeanparpaillon** [comment]
@ffringel : I've just committed a new test in dbus_client_SUITE for large string and I can not reproduce the bug...
Maybe the bug comes from the application using erlang-dbus, and not erlang-dbus itself.

I let the bug open until it is resolved in the other app...

**Comment by ffringel** [comment]
OK

**Comment by cgourdin** [comment]
Hello,
It's not a java related issue, and i have still the problem. 

Kindly find attached the files :
Erocci works with this file : 
[good_docker-schema.xml.txt](https://github.com/erocci/erocci_backend_dbus/files/197330/good_docker-schema.xml.txt)

Erocci doesn't works with this file : 
[fail_docker-schema.xml.txt](https://github.com/erocci/erocci_backend_dbus/files/197331/fail_docker-schema.xml.txt)

This is the log on failure :
[erocci_log.txt](https://github.com/erocci/erocci_backend_dbus/files/197335/erocci_log.txt)


To check if this is a dbus issue, i have made a simple client dbus java and a simple server dbus java here :  [https://github.com/cgourdin/simpledbusserver](url)
And here : [https://github.com/cgourdin/simpledbusclient](url)

Note that I didn't have this issue on call Get() method or any other method returning String in java so it's an erlang issue.

**Comment by jeanparpaillon** [comment]
Can not reproduce
