### ISSUE TITLE
disable logging

### ISSUE THREAD

**Issue by slashmili** [lizenn/erlang-dbus#26]
Hi there,

I have a silly question, how can I disable logging in this project?

Is it possible to add an option to to main app and configure the log level?

**Comment by jeanparpaillon** [comment]
dbus is using regular erlang logger, as you can find here:
https://github.com/lizenn/erlang-dbus/blob/master/include/dbus.hrl

I have never tried to disable specific logging but you can find documentation here: http://erlang.org/doc/system_principles/error_logging.html

**Comment by slashmili** [comment]
Thanks
