### ISSUE TITLE
make test: example-service.py not started

### ISSUE THREAD

**Issue by frehberg** [lizenn/erlang-dbus#5]
Executing 'make test' some tests fail due to missing DBUS service 'net.lizenn.dbus.SampleService'

Either the README should state that the following Python script should be started before running 'make test' or the corresponding Makefile rule in file  erlang.mk  should start/stop the script, eg:

```
diff --git a/erlang.mk b/erlang.mk
index 98db78b..39ed906 100644
--- a/erlang.mk
+++ b/erlang.mk
@@ -890,7 +890,9 @@ ct:
 else
 ct: test-build
        @mkdir -p logs/
+       ./test/dbus_client_SUITE_data/example-service.py & echo $$! > /tmp/example-service.pid
        $(gen_verbose) $(CT_RUN) -suite $(addsuffix _SUITE,$(CT_SUITES)) $(CT_OPTS)
+       kill `cat /tmp/example-service.pid`
 endif
```
 

BTW: even if the example-service is available, I see the following error reports, but the test-report shows 0 failures.

=ERROR REPORT==== 13-Aug-2015::06:55:18 ===
Bad input fd in erts_poll()! fd=18, port=#Port<0.2238>, driver=inert_drv, name=inert_drv

**Comment by jeanparpaillon** [comment]
This issue has been fixed in e896beda81d731a2f596856d2f44056eca6afb74
