### ISSUE TITLE
status

### ISSUE THREAD

**Issue by benoitc** [lizenn/erlang-dbus#9]
the project looks interresting but it lacks of a user documentation and/or examples. What is the status about that? Any ETA? Do you have any example I could look at?

**Comment by jeanparpaillon** [comment]
AFAIK, actually the project is only used in another project I'm maintaing, erocci, which uses can consume D-Bus services. The component using dbus is https://github.com/erocci/erocci_backend_dbus/blob/master/src/erocci_backend_dbus.erl 

Sure, it lacks doc and examples :/

The status: 
* consume D-Bus services: ok
* connect through TCP and UNIX socket: ok
* connect through kernel: not ok (but can use unix socket emulation)
* tested: ok. 
  * erocci_backend_dbus includes a Python service with which eorcci_backend_dbus can interact
  * Another implementation of the same D-Bus interface is used in another project (Java): https://github.com/gibello/erocci-dbus-java

TODO:
* expose D-Bus services
* some authentication mechanisms are not implemented, but architectures allows for easy extension (see https://github.com/lizenn/erlang-dbus/blob/master/src/dbus_auth_cookie_sha1.erl, https://github.com/lizenn/erlang-dbus/blob/master/src/dbus_auth_external.erl and https://github.com/lizenn/erlang-dbus/blob/master/src/dbus_auth_anonymous.erl)
* more doc, more examples
* more tests: unit tests regarding (un)marshaling would be really great, even if the above mentioned xample has rather complex interfaces which works both with Python and Java implementations
* provide facilities for standard interfaces: Properties, ObjectManager, etc.
